### ISSUE TITLE
Problem converting a legacy site to this template

### ISSUE THREAD

**Issue by Gomez** [collective/plonetheme.webpacktemplate#18]
Thanks to this template i make great progress in converting a large project to webpack.

I have some libraries and functions i don't want to touch right now and just include as is.

For example this resources (registry.xml:
```
<records prefix="plone.resources/project-functions"
            interface='Products.CMFPlone.interfaces.IResourceRegistry'>
      <value key="js">++theme++project.theme/static/functions.js</value>
</records>
```
functions.js has an helper:
```
function go_to(url) {
/*code*/
}
```
I can get it included in default.js like this: 
```
import(/* webpackChunkName: "project-functions" */ 'project-functions');
```

But how can i expose it into the window? Like this:

window.go_to = go_to;

Similar would be the OpenLayers.js from [collective.geo.openlayers](https://github.com/collective/collective.geo.openlayers/blob/master/src/collective/geo/openlayers/profiles/default/registry.xml#L4). How can i import it in default.js and expose it into the window?

As a test i pasted the go_to function directly into default.js and it worked. Same with OpenLayers.js.

**Comment by datakurre** [comment]
Possibly with
```
    import(/* webpackChunkName: "project-functions" */ 'expose-loader?go_to!project-functions');
```
https://github.com/webpack-contrib/expose-loader  

Btw, keep on posting issue where when you face them. I've been using this latest Webpack 4 iteration with dynamic code-splitting (e.g. loading a chunk only when there is specific body.portal-type) only a few months for now and there are some tricks needed for add-ons like facetednavigation.

**Comment by datakurre** [comment]
When in doubt with imports-loader and expose-loader, add a ``debugger`` line into you resource and let browser inspector stop at the break point there. Just because that might be the fastest way to see the file as it is imported with webpack. The beginning of the file contains lines generated by imports-loader and the end of the file contains the lines generated by expose-loader. Those were helpful for me to understand, what was really happening.

**Comment by Gomez** [comment]
Thanks for the quick answer. Will test it.

**Comment by datakurre** [comment]
One more tip I found from my projects. Those imports can be combined with Promises to do some additional initialization after the module has been loaded.
``` 
Promise.all([
      import(
        /* webpackChunkName: "chunkname" */ "path/to/lib"
      )
    ]).then(args => {
        // do something
    });
```

https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by Gomez** [comment]
Got the site working. Thanks for your help!

Still my webpack configuration is far from good, will further improve and report if needed.

Should we close the issue as this is no real bug?
