### ISSUE TITLE
Plone5.2.1 - requirejs not defined

### ISSUE THREAD

**Issue by Gomez** [collective/plonetheme.webpacktemplate#22]
I noticed this error in the console on every page, but most of the JS works. 

ReferenceError: requirejs is not defined  - config.js:1:1

I try to understand how and where requirejs gets included and why most of the js works. 

The ++resource++schemaeditor.js (Dexterity) for example gives two errors:

ReferenceError: requirejs is not defined config.js:1:1
ReferenceError: require is not defined ++resource++schemaeditor.js:2:1

**Comment by datakurre** [comment]
This should not be on every page.

Search page and some other require this working.

I will check this later. Could confirm that clean project from template does not have this? ( this used to work )

**Comment by Gomez** [comment]
Correct, no error on clean project from template.

**Comment by Gomez** [comment]
Found it. Wrong closing tag in index.html. 

Sorry for the noise!
